FROM httpd:latest
MAINTAINER high-po

ADD ./* /usr/local/apache2/htdocs/

RUN cd /usr/local/apache2/htdocs/
RUN mkdir /usr/local/apache2/htdocs/script
RUN mkdir /usr/local/apache2/htdocs/style
RUN mv /usr/local/apache2/htdocs/script.js /usr/local/apache2/htdocs/script/
RUN mv /usr/local/apache2/htdocs/style.css /usr/local/apache2/htdocs/style/

WORKDIR /usr/local/apache2/htdocs/

EXPOSE 80